/** Compile-time migration contract, pinned to the pre-split public API. */
import type {
  AdoptSuppliedMarkInput,
  AssertTokenStylesLoadedOptions,
  BackdropCheckOptions,
  BackdropContract,
  BackdropElementRuleId,
  BackdropFinding,
  BackdropKind,
  BackdropLoading,
  BackdropReducedMotion,
  BackdropReport,
  BackdropRuleId,
  BackdropScrim,
  BackdropUnchecked,
  BackdropUncheckedReason,
  BrandCssUnchecked,
  BrandFileCoverageCheckOptions,
  BrandFileCoverageFailureReason,
  BrandFileCoverageFinding,
  BrandFileCoverageFindingRule,
  BrandFileCoverageReport,
  BrandFileCoverageUnchecked,
  ClearSpaceResult,
  ComposeLockupInput,
  ContrastException,
  ContrastGateCheckOptions,
  ContrastGateFailureReason,
  ContrastGateFinding,
  ContrastGateFindingRule,
  ContrastGateRelieved,
  ContrastGateResult,
  ContrastGateUnchecked,
  ContrastGateUncheckedReason,
  ContrastLevel,
  ContrastPair,
  IdentityBrandInput,
  IdentityCheckId,
  IdentityCheckJudgement,
  IdentityContrastFinding,
  IdentityContrastResult,
  IdentityContrastVariant,
  IdentityDirection,
  IdentityDirectionKind,
  IdentityFinding,
  IdentityKitJudgement,
  IdentityKitReport,
  IdentityTokenInput,
  IdentityVariantRole,
  IdentityVariantSet,
  IdentityVerdict,
  LockupFontLicence,
  LockupFontOutlining,
  LockupHeader,
  LockupSpec,
  MasterMark,
  MinimumSizeResult,
  MonoReservedRole,
  Oklch,
  OrphanWordPolicy,
  ParsedBrandCss,
  SingleColourLegibilityResult,
  TokenDefinition,
  TokenFamily,
  TypeRecord,
  TypeRecordFinding,
  TypeRecordParseFailure,
  TypeRecordParseResult,
  TypeRecordWrap,
} from "./index.js";
import type { BrandCssReadIssue, BrandCssReadIssueReason, BrandCssReadResult } from "./server.js";

type PreservedPureTypes = [
  AdoptSuppliedMarkInput,
  AssertTokenStylesLoadedOptions,
  BackdropCheckOptions,
  BackdropContract,
  BackdropElementRuleId,
  BackdropFinding,
  BackdropKind,
  BackdropLoading,
  BackdropReducedMotion,
  BackdropReport,
  BackdropRuleId,
  BackdropScrim,
  BackdropUnchecked,
  BackdropUncheckedReason,
  BrandCssUnchecked,
  BrandFileCoverageCheckOptions,
  BrandFileCoverageFailureReason,
  BrandFileCoverageFinding,
  BrandFileCoverageFindingRule,
  BrandFileCoverageReport,
  BrandFileCoverageUnchecked,
  ClearSpaceResult,
  ComposeLockupInput,
  ContrastException,
  ContrastGateCheckOptions,
  ContrastGateFailureReason,
  ContrastGateFinding,
  ContrastGateFindingRule,
  ContrastGateRelieved,
  ContrastGateResult,
  ContrastGateUnchecked,
  ContrastGateUncheckedReason,
  ContrastLevel,
  ContrastPair,
  IdentityBrandInput,
  IdentityCheckId,
  IdentityCheckJudgement,
  IdentityContrastFinding,
  IdentityContrastResult,
  IdentityContrastVariant,
  IdentityDirection,
  IdentityDirectionKind,
  IdentityFinding,
  IdentityKitJudgement,
  IdentityKitReport,
  IdentityTokenInput,
  IdentityVariantRole,
  IdentityVariantSet,
  IdentityVerdict,
  LockupFontLicence,
  LockupFontOutlining,
  LockupHeader,
  LockupSpec,
  MasterMark,
  MinimumSizeResult,
  MonoReservedRole,
  Oklch,
  OrphanWordPolicy,
  ParsedBrandCss,
  SingleColourLegibilityResult,
  TokenDefinition,
  TokenFamily,
  TypeRecord,
  TypeRecordFinding,
  TypeRecordParseFailure,
  TypeRecordParseResult,
  TypeRecordWrap,
];
type PreservedNodeTypes = [BrandCssReadIssue, BrandCssReadIssueReason, BrandCssReadResult];
type Exact<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;
type PureValues = "AA" | "AA_LARGE" | "BACKDROP_BUDGET_CEILING_BYTES" | "BACKDROP_KINDS" | "CONTRAST_PAIRS" | "IDENTITY_MIN_CONTRAST" | "IDENTITY_VARIANT_ROLES" | "IdentityKitValidationError" | "LOCKUP_FONT_OUTLINING" | "LOCKUP_GAP" | "LOCKUP_GAP_RATIO" | "LOCKUP_HEADERS" | "LOCKUP_MARK_HEIGHT" | "LOCKUP_WORDMARK_SIZE" | "LOCKUP_WORDMARK_SIZE_RATIO" | "MASTER_MARK_ICON_SHELL_STYLE" | "MasterMarkValidationError" | "TOKENS" | "TOKEN_FAMILIES" | "TOKEN_STYLES_SENTINEL_PROPERTY" | "TYPE_RECORD_SCHEMA_VERSION" | "adoptSuppliedMark" | "assertTokenStylesLoaded" | "checkBackdropContract" | "checkBackdropElement" | "checkBrandFileCoverage" | "checkClearSpace" | "checkIdentityContrast" | "checkMinimumSize" | "checkSingleColourLegibility" | "checkTokenContrast" | "checkTypeRecord" | "checkTypeRecordOverlay" | "composeLockup" | "contrastPairsForTheme" | "contrastRatio" | "deriveInitials" | "formatParseFailure" | "generateIdentityDirections" | "hexToLinearSRGB" | "iconMarkSvg" | "identityKitReport" | "isPlaceholderAuthoredValue" | "isValidCssColor" | "isValidCssFontFamily" | "judgeIdentityKit" | "luminanceOf" | "oklchToLinearSRGB" | "parseBrandDeclarations" | "parseOklch" | "parseTypeRecord" | "recolorSvg" | "relativeLuminance" | "validateIdentityTokenInput" | "validateMasterMark";
type NodeValues = "assertTailwindMergeVersion" | "readBrandCss";
type PureNamespace = Assert<Exact<keyof typeof import("./index.js"), PureValues>>;
type NodeNamespace = Assert<Exact<keyof typeof import("./server.js"), NodeValues>>;

// @ts-expect-error File-reading types migrated to the Node-only public entry.
import type { BrandCssReadIssue as RemovedBrandCssReadIssue } from "./index.js";

// @ts-expect-error File-reading types migrated to the Node-only public entry.
import type { BrandCssReadIssueReason as RemovedBrandCssReadIssueReason } from "./index.js";

// @ts-expect-error File-reading types migrated to the Node-only public entry.
import type { BrandCssReadResult as RemovedBrandCssReadResult } from "./index.js";
