/** Consumer-owned starter contracts and pure result validation. */
export { admissionExitCode, evaluateAdmission, evaluateHeadInstall, evaluateStarter, evaluateProcessResult, isNormalizedRelativePath, validateStarterRequest } from "./core.js";
export type {
  AdmissionEvaluationInput,
  AdmissionInstall,
  AdmissionReport,
  HeadInstallEvaluationInput,
  HeadInstallIdentity,
  HeadInstallObservation,
  HeadInstallReport,
  HeadInstallRole,
  StarterEvaluationInput,
  StarterFinding,
  StarterHubEvidence,
  StarterPhase,
  StarterReport,
  StarterRequest,
  StarterState,
  ExactPackage,
  InstallReceipt,
  PackageManager,
  ProcessObservation,
  SnapshotFile,
  SnapshotManifest,
  TargetPackage,
  TrustedEvent,
} from "./types.js";
