/**
 * The plain-text alternative — built from the SAME ordered, resolved
 * `{ key, text }` entries `renderEmailDocument.ts` uses to build the HTML
 * body, never by stripping tags off the HTML this package already
 * generated.
 *
 * WHY THAT DIRECTION MATTERS
 * ------------------------------
 * Deriving the plain-text part FROM the HTML string (a tag-stripping
 * regex, an HTML-to-text library) is the failure mode this file exists to
 * avoid: the two parts would be generated by two different code paths that
 * can silently drift apart — a future change to the HTML template (an
 * added wrapper `<div>`, a changed escaping rule) could corrupt the
 * plain-text part, or fail to, in ways nothing here would catch. Building
 * both from ONE shared list of resolved texts (this file takes exactly the
 * same `entries` `buildEmailHtml` in `renderEmailDocument.ts` iterates
 * over) means there is only one source of truth for "what does slot X
 * say," and the HTML/text outputs can only ever differ in FORMATTING, not
 * in CONTENT.
 *
 * FORMATTING
 * ----------
 * Each entry's raw (UN-escaped — `escapeHtml` is an HTML-output concern
 * only; a `text/plain` part has no markup to be safe against) text becomes
 * one paragraph, separated by a single blank line, in the same
 * `orderEntries`-sorted order the HTML body renders in. A trailing
 * newline terminates the whole string, matching the POSIX convention every
 * text file this repository ships already follows.
 */
export function buildPlainText(entries: ReadonlyArray<{ text: string }>): string {
  return entries.map((entry) => entry.text).join("\n\n") + "\n";
}
