import { describe, expect, it } from "vitest";
import { render, screen } from "@testing-library/react";
import * as Icons from "./icons/index.js";

/**
 * Every icon this package ships is generated by the same `createIcon`
 * factory `src/createIcon.test.tsx` already covers directly — this file
 * checks the 32 SHIPPED icons specifically: that each one is real,
 * distinct, and follows the size/color/accessibility contract, and that
 * the count matches what README.md and the PR body claim.
 */

const iconEntries = Object.entries(Icons).filter(
  ([, value]) => typeof value === "object" || typeof value === "function",
) as [string, React.ComponentType<Record<string, unknown>>][];

describe("shipped icon set", () => {
  it("ships exactly 32 icons — the evidence-picked core described in README.md", () => {
    expect(iconEntries.length).toBe(32);
  });

  it("every exported name ends in \"Icon\" (the component-naming convention)", () => {
    for (const [name] of iconEntries) {
      expect(name.endsWith("Icon")).toBe(true);
    }
  });

  it("every icon has a unique displayName matching its export name", () => {
    const displayNames = new Set<string>();
    for (const [name, Component] of iconEntries) {
      const displayName = (Component as { displayName?: string }).displayName;
      expect(displayName).toBe(name);
      expect(displayNames.has(displayName as string)).toBe(false);
      displayNames.add(displayName as string);
    }
  });

  it("every icon renders real SVG markup (at least one path/shape child) when decorative", () => {
    for (const [name, Component] of iconEntries) {
      const { unmount } = render(<Component decorative data-testid={name} />);
      const svg = screen.getByTestId(name);
      expect(svg.tagName.toLowerCase()).toBe("svg");
      expect(svg.children.length).toBeGreaterThan(0);
      unmount();
    }
  });

  it("every icon strokes with currentColor and never a hardcoded color, for every icon in the set", () => {
    for (const [name, Component] of iconEntries) {
      const { unmount } = render(<Component decorative data-testid={name} />);
      const svg = screen.getByTestId(name);
      expect(svg).toHaveAttribute("stroke", "currentColor");
      expect(svg.getAttribute("fill")).not.toMatch(/^#|^rgb/);
      unmount();
    }
  });

  it("every icon accepts a label and becomes an accessible, named role=img", () => {
    for (const [name, Component] of iconEntries) {
      const { unmount } = render(<Component label={`${name} label`} />);
      const svg = screen.getByRole("img", { name: `${name} label` });
      expect(svg).toBeTruthy();
      unmount();
    }
  });
});
