/**
 * `generateUtilitiesCss` — the `styles/utilities.css` shipped beside
 * `theme.css`. It is a run of single-line `@source inline(...)` directives (Tailwind rejects a string that spans lines) listing every class
 * candidate `scanCompiledCssSources` extracts from this package's own
 * components, so a shared CSS entry can generate this package's utilities
 * without a path-based `@source` on `dist` (which a pnpm symlink can defeat)
 * and without the consumer maintaining a class list.
 *
 * Over-inclusion is harmless here for the reason `class-scan.ts` documents:
 * Tailwind ignores an inline candidate that is not a utility. Candidates
 * containing a quote or backslash are dropped because they cannot sit inside
 * the directive's string literal.
 */

const UNSAFE_CANDIDATE_RE = /["'\\\s]/;

export function generateUtilitiesCss(candidates: readonly string[]): string {
  const safe = [...new Set(candidates)].filter((c) => c.length > 0 && !UNSAFE_CANDIDATE_RE.test(c)).sort();
  const lines: string[] = [];
  let line = "";
  for (const c of safe) {
    if (line.length + c.length + 1 > 100 && line.length > 0) {
      lines.push(line);
      line = "";
    }
    line = line.length === 0 ? c : `${line} ${c}`;
  }
  if (line.length > 0) lines.push(line);
  return [
    "/* Generated by `npm run generate:compiled-css`; do not edit. */",
    "/* Import after `@import \"tailwindcss\"` and `theme.css`: generates this package's utilities without a path-based source directive. */",
    ...lines.map((l) => `@source inline("${l}");`),
    "",
  ].join("\n");
}
