/**
 * This file is NOT a public entry point — `package.json` deliberately
 * declares no `"."` export. Import from `@vespeneventures/ui/atoms` or
 * `@vespeneventures/ui/blocks` instead; see the README for why the ladder
 * (atoms → blocks → views) is kept explicit at the import site rather than
 * flattened through a root barrel. This barrel exists only so the same
 * names are reachable from one place for internal tooling (see
 * `scripts/check-readme-parity.mjs` in the repository root, which reads
 * `src/index.ts` as every package's canonical export list); it re-exports
 * exactly what `./atoms/index.js`, `./icons/index.js`, `./blocks/index.js`,
 * `./views/index.js`, `./shell/index.js`, and `./charts/index.js` each
 * export, nothing more.
 */
export {
  Button,
  Icon,
  TextField,
  Badge,
  Card,
  Breadcrumb,
  Link,
  Checkbox,
  Switch,
  Select,
  Textarea,
  Avatar,
  Spinner,
  Menu,
  Dialog,
  Tabs,
  Table,
  Field,
  Skeleton,
  Tooltip,
  Banner,
  RadioGroup,
  Popover,
  DateField,
  ComboBox,
  SearchField,
  FileTrigger,
  Disclosure,
  ProgressBar,
  Separator,
  Chip,
} from "./atoms/index.js";
export type {
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  IconProps,
  IconSize,
  IconAccessibilityProps,
  IconNode,
  TextFieldProps,
  BadgeProps,
  BadgeVariant,
  CardProps,
  BreadcrumbProps,
  BreadcrumbItemProps,
  LinkProps,
  LinkVariant,
  CheckboxProps,
  SwitchProps,
  SelectProps,
  SelectOption,
  TextareaProps,
  AvatarProps,
  AvatarSize,
  SpinnerProps,
  SpinnerSize,
  MenuProps,
  MenuItemProps,
  MenuSeparatorProps,
  DialogProps,
  DialogSize,
  DialogHeadingProps,
  TabsProps,
  TabsListProps,
  TabsTabProps,
  TabsPanelProps,
  TableProps,
  TableHeaderProps,
  TableColumnProps,
  TableBodyProps,
  TableRowProps,
  TableCellProps,
  TableSelectAllCheckboxProps,
  TableSelectionCheckboxProps,
  FieldProps,
  FieldRenderProps,
  SkeletonProps,
  SkeletonShape,
  TooltipProps,
  BannerProps,
  BannerVariant,
  RadioGroupProps,
  RadioGroupRadioProps,
  PopoverProps,
  DateFieldProps,
  ComboBoxProps,
  ComboBoxOption,
  SearchFieldProps,
  FileTriggerProps,
  DisclosureProps,
  ProgressBarProps,
  SeparatorProps,
  ChipProps,
} from "./atoms/index.js";

export {
  PageHeader,
  EmptyState,
  DataTable,
  DetailView,
  Pagination,
  Stat,
  Form,
  FieldGroup,
  ConfirmDialog,
  Toolbar,
  NavGrid,
  SectionHeader,
} from "./blocks/index.js";
export type {
  PageHeaderProps,
  EmptyStateProps,
  DataTableProps,
  DataTableColumn,
  DataTableSelectionMode,
  DetailViewProps,
  DetailViewField,
  PaginationProps,
  StatProps,
  StatTrend,
  FormProps,
  FormError,
  FieldGroupProps,
  FieldGroupLayout,
  ConfirmDialogProps,
  ConfirmDialogTone,
  ToolbarProps,
  NavGridProps,
  NavGridItem,
  SectionHeaderProps,
  SectionHeaderLevel,
} from "./blocks/index.js";

export { ErrorView, AuthView } from "./views/index.js";
export type { ErrorViewProps, AuthViewProps } from "./views/index.js";

export { Shell, Toaster, toast } from "./shell/index.js";
export type {
  ShellProps,
  ShellHeaderProps,
  ShellSideNavProps,
  ShellMainProps,
  ShellRailProps,
  ShellFooterProps,
  ToasterProps,
  ToastFunction,
  ToastHandle,
  ToastOptions,
  ToastRecord,
  ToastVariant,
} from "./shell/index.js";

export { ChartFrame, BarChart, LineChart, Sparkline } from "./charts/index.js";
export type {
  ChartFrameProps,
  ChartMargin,
  ChartAxisTick,
  ChartLegendItem,
  ChartTableSpec,
  PlotArea,
  BarChartProps,
  BarChartSeries,
  LineChartProps,
  LineChartSeries,
  SparklineProps,
} from "./charts/index.js";

export {
  AlertTriangle,
  BookOpen,
  Box,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  ExternalLink,
  FileText,
  Folder,
  Grid3x3,
  Home,
  Info,
  List,
  Lock,
  Monitor,
  Moon,
  Plug,
  Receipt,
  Search,
  Settings,
  Sun,
  User,
  Users,
  X,
  XCircle,
} from "./icons/index.js";
