/** @deprecated Migrate to `@vespeneventures/governance/gates`. */
export {
  checkCredentialInventory,
  checkCredentialSurfaceDrift,
  checkLocalSecretFiles,
  checkProviderResourceNames,
  checkSecretName,
  checkSecretReadiness,
  checkValueFreeSecretCatalog,
  computeBuildOrder,
  detectRawSecretReads,
  runFoundationCheck,
  verifyPolicyBindings,
} from "@vespeneventures/governance/gates";
export type {
  BuildOrderResult,
  Catalog,
  CatalogEntry,
  CatalogFinding,
  CredentialInventory,
  CredentialInventoryEntry,
  CredentialSurfaceObservation,
  Finding,
  FoundationReport,
  LocalFileObservation,
  LocalSecretFileOptions,
  PolicyBinding,
  PolicyCheck,
  PolicyCheckResult,
  ProviderResourceNamingRule,
  ProviderResourceObservation,
  RawSecretReadOptions,
  RunFoundationCheckOptions,
  SecretCatalogGateDocument,
  SecretCatalogGateEntry,
  SecretGateFinding,
  SecretReadinessObservation,
} from "@vespeneventures/governance/gates";
