import type { CopyRegistry } from "@clossys/writer";

/**
 * Approved placeholder copy for `publisher-preview` fixtures only. Same
 * `CopyRegistry` shape Writer's render path expects; not a consumer store.
 */
const FIXTURE_COPY: Record<string, string> = {
  "preview.sectioned.hero.eyebrow": "New",
  "preview.sectioned.hero.heading": "A placeholder home page",
  "preview.sectioned.hero.description": "Fixture description.",
  "preview.sectioned.features.heading": "Features",
  "preview.sectioned.features.description": "Feature fixture.",
  "preview.sectioned.features.one.heading": "First feature",
  "preview.sectioned.features.one.description": "First feature description.",
  "preview.sectioned.features.two.heading": "Second feature",
  "preview.sectioned.faq.heading": "Questions",
  "preview.sectioned.faq.description": "FAQ fixture.",
  "preview.sectioned.faq.one.question": "Why this?",
  "preview.sectioned.faq.one.answer": "Because it is validated.",
  "preview.sectioned.steps.heading": "Steps",
  "preview.sectioned.steps.one.ordinal": "1",
  "preview.sectioned.steps.one.label": "First",
  "preview.sectioned.steps.one.heading": "Start here",
  "preview.sectioned.steps.one.description": "Start fixture.",
  "preview.sectioned.status.heading": "Readiness",
  "preview.sectioned.status.available": "Available",
  "preview.sectioned.status.partial": "Partial",
  "preview.sectioned.status.planned": "Planned",
  "preview.sectioned.status.not-offered": "Not offered",
  "preview.sectioned.status.group.heading": "Core",
  "preview.sectioned.status.item.label": "Fixture capability",
  "preview.sectioned.stats.heading": "Metrics",
  "preview.sectioned.stats.one.label": "Active users",
  "preview.sectioned.stats.one.value": "2,481",
  "preview.sectioned.stats.one.delta": "+12%",
  "preview.sectioned.pricing.eyebrow": "Plans",
  "preview.sectioned.pricing.heading": "Pricing",
  "preview.sectioned.pricing.description": "Fixture pricing.",
  "preview.sectioned.pricing.tier.name": "Team",
  "preview.sectioned.pricing.tier.price": "$12",
  "preview.sectioned.pricing.tier.feature": "Unlimited seats",
  "preview.sectioned.pricing.tier.cta": "Start trial",
  "preview.sectioned.testimonial.heading": "Proof",
  "preview.sectioned.testimonial.quote": "It just works.",
  "preview.sectioned.testimonial.name": "Fixture Author",
  "preview.sectioned.testimonial.role": "Customer",
  "preview.sectioned.stat.heading": "Outcomes",
  "preview.sectioned.stat.label": "Uptime",
  "preview.sectioned.stat.value": "99.9%",
  "preview.sectioned.stat.delta": "+0.1%",
  "preview.document.title": "Privacy notice",
  "preview.document.summary": "How this fixture handles data.",
  "preview.document.date": "Effective today",
  "preview.document.section": "Details",
  "preview.document.body": "Fixture body.",
};

export const PREVIEW_FIXTURE_COPY_REGISTRY: CopyRegistry = {
  id: "publisher-preview-fixtures",
  locale: "en",
  revision: "1",
  source: { kind: "consumer", reference: "packages/publisher/src/preview/fixture-copy-registry" },
  entries: Object.entries(FIXTURE_COPY).map(([id, text]) => ({
    id,
    text,
    context: "publisher-preview fixture",
    status: "approved",
  })),
};
